name: Auto Deploy INSIGHT

# Kịch bản này sẽ tự động chạy khi tạo một bản "Release" mới trên GitHub
on:
  release:
    types: [published]

jobs:
  deploy:
    # Chỉ định chạy trên con Runner mà anh sắp cài đặt trên Ubuntu
    runs-on: self-hosted 
    
    steps:
      - name: Deploy Code
        run: |
          # Di chuyển vào thư mục dự án
          cd /home/cuong-deploy/API-Testing
          
          # 2. Xóa bỏ mọi thay đổi phát sinh trên server để tránh lỗi khi cập nhật code
          # Điều này giúp lệnh pull luôn mượt mà
          git reset --hard origin/main
          
          # 3. Kéo code mới nhất từ nhánh main của GitHub về VPS
          git pull origin main
          
          # 4. Yêu cầu Docker dựng lại (Build) các Image mới và khởi chạy container
          # Lệnh này sẽ tự cập nhật các thay đổi trong source code của anh
          docker compose up -d --build
          
          # 5. Xóa bỏ các bản build cũ (dangling images) để tiết kiệm 30GB SSD của VPS
          docker image prune -f
